#server.port: 8081

spring:
  flyway:
    enabled: true
    # 迁移前校验 SQL 文件是否存在问题
    validate-on-migrate: true
    # 生产环境一定要关闭
    clean-disabled: true
    # 校验路径下是否存在 SQL 文件
    check-location: false
    # 最开始已经存在表结构，且不存在 flyway_schema_history 表时，需要设置为 true
    baseline-on-migrate: true
    # 基础版本 0
    baseline-version: 0


  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test2?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource

#  security:
#    user:
#      name: test
#      password: test

  redis:
    database: 0
    # Redis服务器地址
    host: localhost
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:

  lettuce:
    pool:
      max-active: 20
      max-wait: -1ms
      max-idle: 10
      min-idle: 2

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration.map-underscore-to-camel-case: true



jwtSecret: nTAoEXfHtTqEot9CisSwYbB1KUl02QVKnTAoEXfHtTqEot9CisSwYbB1KUl02QVKnTAoEXfHtTqEot9CisSwYbB1KUl02QVK

sessionOutTimeSeconde: 300